package mdteam.ait.client.animation.console.coral;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

import static mdteam.ait.client.animation.AnimationConstants.STEP;

public class CoralAnimations {

    public static final Animation CORAL_CONSOLE_DEMAT_ANIMATION = Animation.Builder.create(9f).looping()
            .addBoneAnimation("top7",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.84f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.08f, AnimationHelper.createTranslationalVector(0f, -4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.64f, AnimationHelper.createTranslationalVector(0f, -4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.36f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.92f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.6f, AnimationHelper.createTranslationalVector(0f, -4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.16f, AnimationHelper.createTranslationalVector(0f, -4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.88f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.44f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.16f, AnimationHelper.createTranslationalVector(0f, -4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.72f, AnimationHelper.createTranslationalVector(0f, -4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.44f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9f, AnimationHelper.createTranslationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("bottom",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.84f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.08f, AnimationHelper.createTranslationalVector(0f, 4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.64f, AnimationHelper.createTranslationalVector(0f, 4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.36f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.92f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.6f, AnimationHelper.createTranslationalVector(0f, 4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.16f, AnimationHelper.createTranslationalVector(0f, 4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.88f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.44f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.16f, AnimationHelper.createTranslationalVector(0f, 4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.72f, AnimationHelper.createTranslationalVector(0f, 4.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.44f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9f, AnimationHelper.createTranslationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("bone40",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC))).build();
    public static final Animation CORAL_CONSOLE_POWER_OFF_ANIMATION = Animation.Builder.create(4f)
            .addBoneAnimation("bone10",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone11",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone12",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone45",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(2f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone57",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone60",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone58",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.0416767f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone59",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone66",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone66",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 50f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone67",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.25f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone67",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(0f, 0f, -27.5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone74",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone74",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 40f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("top7",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bottom",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation CONSOLE_CORAL_IDLE_ANIMATION = Animation.Builder.create(10f).looping()
            .addBoneAnimation("panels4",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("panels5",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(7.167667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("box2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("ball4",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone10",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.125f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.7083435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(5.834333f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.875f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(10f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("lights2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone59",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(5f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(9f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(10f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone48",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone68",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone66",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.676667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone66",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(10f, AnimationHelper.createRotationalVector(0f, 0f, 360f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone67",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 110f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.167667f, AnimationHelper.createRotationalVector(0f, 0f, 110f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.676667f, AnimationHelper.createRotationalVector(0f, 0f, -72.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("bone74",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.6766667f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.75f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.834333f, AnimationHelper.createRotationalVector(0f, 0f, 155f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.416767f, AnimationHelper.createRotationalVector(0f, 0f, 190f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("panels3",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone22",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone11",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.7083435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.9167665f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.625f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.834333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(9f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone12",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.3433335f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.625f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(5.458343f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.041677f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(8.458344f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone32",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone57",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone60",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("hammer",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone40",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.125f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.2083435f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.3433335f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.458343f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.541677f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.676667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.75f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.875f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("crank2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("top7",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bottom",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone58",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(7f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP),
                            new Keyframe(9f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(10f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    STEP))).build();

}
