package dev.amble.ait.client.animation.console.borealis;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class BorealisAnimations {
    public static final Animation CONSOLE_ROTOR_MATERIALIZE = Animation.Builder.create(21.5f).looping()
            .addBoneAnimation("bone110",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leaf1",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf3",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf4",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf5",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf6",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20.25f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(21.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(1.2f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(1.2f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(1.2f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.416768f, AnimationHelper.createRotationalVector(0.5f, 0f, -0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(20.25f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(21.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .build();
    public static final Animation CONSOLE_ROTOR_INFLIGHT = Animation.Builder.create(6f).looping()
            .addBoneAnimation("bone110",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leaf1",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf3",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf4",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf5",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf6",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(1.2f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .build();
    public static final Animation CONSOLE_ROTOR_DEMATERIALIZE = Animation.Builder.create(19.5f).looping()
            .addBoneAnimation("bone110",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leaf1",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf3",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf4",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf5",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leaf6",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(75f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createTranslationalVector(0f, -9f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(1.2f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(1.2f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(1.2f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(-1.2f, 5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .build();
    public static final Animation CONSOLE_IDLE_WHEATLEY = Animation.Builder.create(2.5f).looping()
            .addBoneAnimation("wheatleyeye",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(-1f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0.75f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.5f, -0.75f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0.75f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(-1f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .build();
}
