package mdteam.ait.client.animation.console.hartnell;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;
import org.joml.Vector3f;

import static mdteam.ait.client.animation.AnimationConstants.STEP;

public class HartnellAnimations {

    public static final Animation ROTOR = Animation.Builder.create(3.4f).looping()
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.68f, AnimationHelper.createTranslationalVector(0f, -4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.36f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("compass",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.68f, AnimationHelper.createRotationalVector(0f, 180f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.36f, AnimationHelper.createRotationalVector(0f, 360f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();

    public static final Animation HARTNELL_INFLIGHT_ANIMATION = Animation.Builder.create(8f).looping()
            .addBoneAnimation("rotor",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, -4f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, -4f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("compass",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(8f, AnimationHelper.createRotationalVector(0f, -360f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone166",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP)))
            .addBoneAnimation("bone169",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP)))
            .addBoneAnimation("bone167",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone170",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone168",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone171",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone91",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2.7916765f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(5.041677f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.208343f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(6.834333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.416767f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP)))
            .addBoneAnimation("bone93",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.75f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(3.9167665f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(5.25f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(6.416767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.343333f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.676667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone92",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(3.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(4.208343f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(4.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(5.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(6.167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.083433f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.416767f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.958343f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone94",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.0416765f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(4.083433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(4.958343f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(5.541677f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.041677f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(6.791677f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.25f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.791677f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone95",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.7916766f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(1.0834333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.9167667f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.0834335f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(3.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(4.208343f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(4.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(5.416767f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(5.708343f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(5.958343f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(6.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.958343f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.375f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.676667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone109",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.4583433f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.9583434f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.4167667f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.6766667f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.0834335f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.3433335f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.7916765f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.2916765f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.75f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.416767f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.834333f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.375f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.791677f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.041677f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.916767f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.167667f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.625f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("bone116",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(3.5834335f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(4.791677f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(5.834333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(6.958343f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.291677f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.583433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.834333f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone126",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.125f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.625f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.9167667f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.4167665f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.6766665f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.2083435f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.7916765f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.291677f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.583433f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.083433f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.541677f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.167667f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.676667f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.958343f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.458343f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.875f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("bone127",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 20f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 40f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.625f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.0834335f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.9583435f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.25f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.7083435f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.083433f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.416767f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.541677f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.916767f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.625f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.125f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.708343f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.167667f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.458343f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.916767f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("bone131",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -0.7f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0.1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, -0.3f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0.7f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.125f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.6766665f, AnimationHelper.createTranslationalVector(0f, 0f, 0.6f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.2916765f, AnimationHelper.createTranslationalVector(0f, 0f, -0.6f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.041677f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.5f, AnimationHelper.createTranslationalVector(0f, 0f, -0.6f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.958343f, AnimationHelper.createTranslationalVector(0f, 0f, 0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.416767f, AnimationHelper.createTranslationalVector(0f, 0f, -0.7f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 0f, -0.3f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.583433f, AnimationHelper.createTranslationalVector(0f, 0f, -0.6f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.5f, AnimationHelper.createTranslationalVector(0f, 0f, -0.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.676667f, AnimationHelper.createTranslationalVector(0f, 0f, -0.2f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8f, AnimationHelper.createTranslationalVector(0f, 0f, -0.7f),
                                    Transformation.Interpolations.CUBIC))).build();

    public static final Animation HARTNELl_IDLE_ANIMATION = Animation.Builder.create(8f).looping()
            .addBoneAnimation("bone33",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone91",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.5416765f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(5.167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone93",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.0834335f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.0834335f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(4.083433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.291677f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.958343f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone92",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.3433335f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2.625f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(4.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(5.875f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.083433f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7.676667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone94",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(7f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP)))
            .addBoneAnimation("bone95",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.75f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(4.083433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(5.167667f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(6.583433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(7.416767f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP)))
            .addBoneAnimation("m_sensor_1",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone109",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167666f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4583435f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.6766665f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.2083435f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.4167665f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5834335f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.625f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.7916765f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.676667f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.875f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.083433f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.75f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.958343f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.167667f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.375f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.583433f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.708343f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.791677f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.916767f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.125f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.375f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.583433f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.791677f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone116",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP),
                            new Keyframe(4.625f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(6.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    STEP)))
            .addBoneAnimation("bone126",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4167667f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.625f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.208343f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.416767f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.583433f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.791677f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone127",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(0f, -8.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, AnimationHelper.createRotationalVector(0f, -27.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167666f, AnimationHelper.createRotationalVector(0f, -7.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5834335f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5834335f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.8343335f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.125f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.834333f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.125f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.375f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.916767f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.167667f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.416767f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.75f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7f, AnimationHelper.createRotationalVector(0f, -40f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone131",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0416765f, AnimationHelper.createTranslationalVector(0f, 0f, 0.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4583435f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.375f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.9583435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.375f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.708343f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.291677f, AnimationHelper.createTranslationalVector(0f, 0f, -0.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.708343f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.041677f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.583433f, AnimationHelper.createTranslationalVector(0f, 0f, 0.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.834333f, AnimationHelper.createTranslationalVector(0f, 0f, 0.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.125f, AnimationHelper.createTranslationalVector(0f, 0f, 0.6f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.5f, AnimationHelper.createTranslationalVector(0f, 0f, -0.75f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("compass",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(8f, AnimationHelper.createRotationalVector(0f, -180f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bone166",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone169",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone167",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone170",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(5.343333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone168",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP)))
            .addBoneAnimation("bone171",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(4f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP),
                            new Keyframe(6.676667f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(8f, AnimationHelper.createScalingVector(1f, 0f, 1f),
                                    STEP))).build();

}
